### ISSUE TITLE
I'm having this issue with python pip. Python Version is 3.7.8 and pip version is 20.1.1.

### ISSUE THREAD

**Issue by NishilSavla** [NishilSavla/ideal-goggles#1]

**Comment by NishilSavla** [comment]
D:\Python>python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\lib\site-packages\pip\__main__.py", line 26, in <module>
    sys.exit(_main())
  File "D:\Python\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "D:\Python\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
    module = importlib.import_module(module_path)
  File "D:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Python\lib\site-packages\pip\_internal\commands\install.py", line 24, in <module>
    from pip._internal.cli.req_command import RequirementCommand, with_cleanup
  File "D:\Python\lib\site-packages\pip\_internal\cli\req_command.py", line 16, in <module>
    from pip._internal.index.package_finder import PackageFinder
  File "D:\Python\lib\site-packages\pip\_internal\index\package_finder.py", line 21, in <module>
    from pip._internal.index.collector import parse_links
  File "D:\Python\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
    from pip._vendor import html5lib, requests
  File "D:\Python\lib\site-packages\pip\_vendor\html5lib\__init__.py", line 25, in <module>
    from .html5parser import HTMLParser, parse, parseFragment
  File "D:\Python\lib\site-packages\pip\_vendor\html5lib\html5parser.py", line 7, in <module>
    from . import _inputstream
  File "D:\Python\lib\site-packages\pip\_vendor\html5lib\_inputstream.py", line 9, in <module>
    from pip._vendor import webencodings
ImportError: cannot import name 'webencodings' from 'pip._vendor' (D:\Python\lib\site-packages\pip\_vendor\__init__.py)


This is the error I'm getting.
